DROP TABLE IF EXISTS public.users;

CREATE TABLE public.users (
	id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	name varchar NOT NULL,
	email varchar NOT NULL,
	CONSTRAINT users_pk PRIMARY KEY (id)
);
